version: '2'
services:
  ph:
    image: communecter/co2-install-dev:latest
    volumes:
      - ./code:/code
      #- ./code/data/db:/data/db
      - mongodb:/data/db
    depends_on:
      - front
volumes:
  mongodb:
  mongodb_config: