version: '2'
services:
  mongo:
    image: mongo:3.4
    volumes:
      - ./code/data/db:/data/db
    ports:
      - "5017:27017"
  front:
    build: docker-front
    ports:
      - "5080:80"
      - "5443:443"
      - "5901:9001"
    volumes:
      - ./code:/code
      - ./code/data/db:/data/db
      - ./code/log:/var/log/nginx
    depends_on:
      - mongo
